[tool.pylint.'MESSAGES CONTROL']
disable = [
    "missing-docstring",
    "invalid-name",
    "logging-fstring-interpolation",
    "unspecified-encoding",
    "too-many-branches",
    "too-many-locals",
    "return-in-finally",
    "broad-exception-caught",
    "too-many-statements",
    "lost-exception",
    "import-error"
]

[tool.pylint.'FORMAT']
max-line-length = 150
